/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminClinicasNovaRouteImport } from './routes/admin.clinicas.nova'
import { Route as AdminClinicasIdRouteImport } from './routes/admin.clinicas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClinicasNovaRoute = AdminClinicasNovaRouteImport.update({
  id: '/admin/clinicas/nova',
  path: '/admin/clinicas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClinicasIdRoute = AdminClinicasIdRouteImport.update({
  id: '/admin/clinicas/$id',
  path: '/admin/clinicas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/c/$slug': typeof CSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clinicas/$id': typeof AdminClinicasIdRoute
  '/admin/clinicas/nova': typeof AdminClinicasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/c/$slug': typeof CSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clinicas/$id': typeof AdminClinicasIdRoute
  '/admin/clinicas/nova': typeof AdminClinicasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/c/$slug': typeof CSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clinicas/$id': typeof AdminClinicasIdRoute
  '/admin/clinicas/nova': typeof AdminClinicasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/c/$slug'
    | '/admin/'
    | '/admin/clinicas/$id'
    | '/admin/clinicas/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/c/$slug'
    | '/admin'
    | '/admin/clinicas/$id'
    | '/admin/clinicas/nova'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/c/$slug'
    | '/admin/'
    | '/admin/clinicas/$id'
    | '/admin/clinicas/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CSlugRoute: typeof CSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClinicasIdRoute: typeof AdminClinicasIdRoute
  AdminClinicasNovaRoute: typeof AdminClinicasNovaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clinicas/nova': {
      id: '/admin/clinicas/nova'
      path: '/admin/clinicas/nova'
      fullPath: '/admin/clinicas/nova'
      preLoaderRoute: typeof AdminClinicasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clinicas/$id': {
      id: '/admin/clinicas/$id'
      path: '/admin/clinicas/$id'
      fullPath: '/admin/clinicas/$id'
      preLoaderRoute: typeof AdminClinicasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  CSlugRoute: CSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClinicasIdRoute: AdminClinicasIdRoute,
  AdminClinicasNovaRoute: AdminClinicasNovaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
